services:
  auction_app:
    env_file:
      - .env
    command: /bin/sh -c "alembic -c alembic.ini upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug"
    volumes:
      - ./src:/app/src
