services:
  auction_app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: auction_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - auction_db
    command: /bin/sh -c "alembic -c alembic.ini upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4 --log-level info"

  auction_db:
    image: postgres:15.6-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: auction_db
    ports:
      - "5434:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

volumes:
  db_data:
